#================== User API ================#

### GET USER
GET http://localhost:8000/api/v1/user

### Register User

POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
  "name":"John Doe",
  "email":"johnnydoe@emale.com",
  "password":"1234567890"
}


### Login  USER 
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "name":"John Doe",
  "email":"johnnydoe@emale.com",
  "password":"1234567890"
}


#================== Expenses API ================#

###GET expenses
GET http://localhost:8000/api/v1/expenses

###POST expenses
POST http://localhost:8000/api/v1/expenses
Content-Type: application/json

{
  "title":"Momo",
  "amount":"$10",
  "date":"2020-01-02",
  "userID":"6279e0c2a4dc02f726658bd1"
}

###DELETE expenses
DELETE http://localhost:8000/api/v1/expenses